language: java
jdk:
- oraclejdk8
before_install: mvn install -DskipTests=true -DfinalName=Dumper-$TRAVIS_TAG
before_deploy: mvn deploy:deploy-file -Durl=file://$TRAVIS_BUILD_DIR/dependencies/ -Dfile=sqlite-jdbc.jar -DgroupId=org.xerial -DartifactId=sqlite-jdbc -Dpackaging=jar -Dversion=3.7.15-SNAPSHOT
deploy:
  provider: releases
  api_key:
    secure: CbqCFi+Csjvhv5DJYcvNMzVdkCFnIuiG3M3cstzSZzmVQGg3Dh1NOXTzm3TJyVoJZAogbm+UAnsgMrMhPZcQRlHKP53SO2lYfBkDrVH+mttBOdWuEkF4TRUo6Smb41FwO1LpGERlxTYtArDMiQrRE1laRL7rXTTJKUS5xpwuwL4=
  file: target/Dumper-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true
